<a href="https://colab.research.google.com/github/nargesalavi/Quantum-Open-Source-Foundation-Mentorship/blob/master/QNN_Optimization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tensorflow==2.1.0

In [ ]:
!pip install tensorflow-quantum

In [3]:
import tensorflow as tf
import tensorflow_quantum as tfq
import cirq
import sympy
import numpy as np

# visualization tools
%matplotlib inline
import matplotlib.pyplot as plt

In [4]:
qubits = cirq.GridQubit.rect(1, 4)

In [5]:
def generate_even_block(block_number):
    """ Function for generating the even blocks
        block_number: Block number, it has to be even.
        return: ciq.Circuit """
    params = sympy.symbols(['theta_{}'.format(n) for n in range((block_number-1)*4,block_number*4)])

    # create the parameterized circuit
    circuit = cirq.Circuit(
        cirq.rz(params[0])(qubits[0]),
        cirq.rz(params[1])(qubits[1]),
        cirq.rz(params[2])(qubits[2]),
        cirq.rz(params[3])(qubits[3]),
        cirq.CZ(qubits[0],qubits[1]),
        cirq.CZ(qubits[0],qubits[2]),
        cirq.CZ(qubits[0],qubits[3]),
        cirq.CZ(qubits[1],qubits[2]),
        cirq.CZ(qubits[1],qubits[3]),
        cirq.CZ(qubits[2],qubits[3])
    )
    
    return circuit

In [6]:
def generate_odd_block(block_number):
    """ Function for generating the odd blocks
        block_number: Block number, it has to be odd.
        return: ciq.Circuit """
    params = sympy.symbols(['theta_{}'.format(n) for n in range((block_number-1)*4,block_number*4)])

    # create the parameterized circuit
    circuit = cirq.Circuit(
        cirq.rx(params[0])(qubits[0]),
        cirq.rx(params[1])(qubits[1]),
        cirq.rx(params[2])(qubits[2]),
        cirq.rx(params[3])(qubits[3])
    )
    
    return circuit

In [7]:
def generate_qnn(l):
    """ Function for generating qnn, containing l number of layers.
        l: number of layers, each layer contains one odd and one even block.
        return: ciq.Circuit """
    circuit = cirq.Circuit()
    for i in range(1,2*l+1):
        if i % 2 == 1:
            circuit += generate_odd_block(i)
        else:
            circuit += generate_even_block(i)
        
    return circuit

In [8]:
l=1
qnn = generate_qnn(l)
print(qnn)

                                               ┌──┐
(0, 0): ───Rx(theta_0)───Rz(theta_4)───@───@────@─────────────
                                       │   │    │
(0, 1): ───Rx(theta_1)───Rz(theta_5)───@───┼────┼@────@───────
                                           │    ││    │
(0, 2): ───Rx(theta_2)───Rz(theta_6)───────@────┼@────┼───@───
                                                │     │   │
(0, 3): ───Rx(theta_3)───Rz(theta_7)────────────@─────@───@───
                                               └──┘


In [9]:
params = tf.zeros([1,8*l ], tf.float32)
print(params)
params_names = sympy.symbols(['theta_{}'.format(n) for n in range(8*l)])

tf.Tensor([[0. 0. 0. 0. 0. 0. 0. 0.]], shape=(1, 8), dtype=float32)


In [11]:
state_layer = tfq.layers.State()
state = state_layer(qnn, symbol_names=params_names, symbol_values=params)
print(state)

Instructions for updating:
reduction_indices is deprecated, use axis instead
<tf.RaggedTensor [[(1+0j), 0j, 0j, 0j, 0j, 0j, 0j, 0j, 0j, 0j, 0j, 0j, 0j, 0j, 0j, 0j]]>


In [12]:
random_circuit = cirq.testing.random_circuit(qubits = qubits,n_moments = np.random.randint(low=1,high=5),\
                                                                op_density = 0.99999999)
print(random_circuit)
random_circuit = tfq.layers.State()(random_circuit)
print(random_circuit)

           ┌──────┐
(0, 0): ────iSwap─────X───×───────
            │         │   │
(0, 1): ────┼─────────@───×───────
            │
(0, 2): ────┼────Y────────iSwap───
            │             │
(0, 3): ────iSwap─────Y───iSwap───
           └──────┘
<tf.RaggedTensor [[(-1.910685465164705e-15+0j), (-3.82137093032941e-15+4.371138828673793e-08j), (-3.82137093032941e-15+4.371138828673793e-08j), (-1-8.742277657347586e-08j), 0j, 0j, 0j, 0j, 0j, 0j, 0j, 0j, 0j, 0j, 0j, 0j]]>


In [42]:
def states_distance(state,target):
  diff = state[0] - target[0]
  diff = tf.reshape(diff, [16, 1])
  conjugate_transposed_state = tf.transpose(diff,conjugate=True)
  return tf.tensordot(conjugate_transposed_state, diff, axes = 1)

In [43]:
a = states_distance(state,random_circuit)
print(a)

tf.Tensor([[2.+0.j]], shape=(1, 1), dtype=complex64)


In [15]:
adam_optimizer = tf.keras.optimizers.Adam(learning_rate=0.005)

In [44]:
distances = []
for i in range(1000):
  with tf.GradientTape() as tape:
    tape.watch(params)
    state = state_layer(qnn, symbol_names=params_names, symbol_values=params)
    distance = states_distance(state,random_circuit)
  distances.append(distance)
  gradients = tape.gradient(distance,params)
  adam_optimizer.apply_gradients(zip(gradients, params))



LookupError: ignored

In [31]:
x = np.arange(4).reshape(4, 1)
print(x)


[[0]
 [1]
 [2]
 [3]]


In [32]:
y = np.arange(4).reshape(1, 4)
print(y)


[[0 1 2 3]]


In [37]:
tf.tensordot(y, x, axes = 1)

<tf.Tensor: shape=(1, 1), dtype=int64, numpy=array([[14]])>